apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdr
  labels:
    app: sdr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdr
  template:
    metadata:
      labels:
        app: sdr
    spec:
      containers:
        - name: sdr
          image: graafnet/shadowpulse-sdr:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 5556
              name: fft
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
                #- name: SDR_DEVICE
                #value: rtlsdr
                #- name: RTLSDR_ARGS
                #value: rtl=0
            - name: SDR_DEVICE
              value: hackrf
            # - name: SDR_DEVICE
            #   value: dummy
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
          securityContext:
            privileged: true
          volumeMounts:
            - name: usbdev
              mountPath: /dev/bus/usb
      volumes:
        - name: usbdev
          hostPath:
            path: /dev/bus/usb
            type: Directory