apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  labels:
    app: shadowpulse
    app.watchgrid.io/name: shadowpulse
    app.watchgrid.io/managed-by: watchgrid
data:
  nginx.conf: |
    worker_processes 1;

    events { worker_connections 1024; }

    http {
        include       mime.types;
        default_type  application/octet-stream;

        sendfile        on;
        keepalive_timeout  65;

        server {
            listen 80;
            server_name _;

            root /usr/share/nginx/html;
            index index.html;

            # Serve static files and rewrite SPA routes
            location / {
                try_files $uri /index.html;
                # Rewrite hard-coded backend URLs in built JS/HTML to relative paths
                sub_filter 'http://localhost:8000' '/api';
                # For WebSockets we want WEBSOCKET_URL to be empty so `${WEBSOCKET_URL}/ws/...` => '/ws/...'
                sub_filter 'ws://localhost:8000' '';
                sub_filter_once off;
                sub_filter_types application/javascript text/html;
            }

            # API proxy to SDR service in cluster (now localhost since both containers are in same pod)
            location /api/ {
                proxy_pass http://localhost:8000/;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            # WebSocket proxy (preserve subpaths like /ws/fft)
            location /ws/ {
                proxy_pass http://localhost:8000/ws/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host $host;
                proxy_read_timeout 3600s;
                proxy_send_timeout 3600s;
            }
        }
    }
